name: "labelller"

on:
  workflow_dispatch:

jobs:
  labeller:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Custom workflow"
        uses: custom-workflow
        with:
          greeting: 'hello'
